displayName: Referer Plugin

type: middleware


import: github.com/moonlightwatch/referer

summary: restrict access by referer

testData:
  Type: white
  EmptyReferer: true
  Domains:
    - "*.baidu.com"
    - "google.com"